'use strict';

const GUIDES = [
  {
    id: 'npm-cache',
    name: 'npm Cache',
    risk: 'safe-cache',
    description: 'Cache paket npm di %LOCALAPPDATA%\\npm-cache. Hanya folder cache; tidak menyentuh node_modules atau paket global.',
    recommendedMethod: 'Gunakan perintah resmi npm untuk memverifikasi dan membersihkan cache.',
    cmdCommands: ['npm cache verify', 'npm cache clean --force'],
    psCommands: ['npm cache verify', 'npm cache clean --force'],
    warnings: ['npm modern mengelola cache otomatis; pembersihan manual jarang diperlukan.', 'npm cache clean --force bersifat agresif; gunakan hanya jika diperlukan.'],
    whatWillHappen: ['Paket perlu diunduh ulang saat install berikutnya.'],
    whatWillNotBeDeleted: ['Kode sumber proyek', 'package.json', 'package-lock.json', 'Paket yang diinstall secara global (npm -g)'],
  },
  {
    id: 'pip-cache',
    name: 'pip Cache',
    risk: 'safe-cache',
    description: 'Cache unduhan pip di %LOCALAPPDATA%\\pip\\Cache. Hanya cache paket, tidak menyentuh virtual environment atau kode proyek.',
    recommendedMethod: 'Gunakan perintah pip bawaan untuk melihat dan membersihkan cache.',
    cmdCommands: ['python -m pip cache dir', 'python -m pip cache info', 'python -m pip cache purge'],
    psCommands: ['python -m pip cache dir', 'python -m pip cache info', 'python -m pip cache purge'],
    warnings: ['python -m pip cache purge menghapus semua cache; paket diunduh ulang saat install berikutnya.'],
    whatWillHappen: ['Paket perlu diunduh ulang saat install berikutnya.'],
    whatWillNotBeDeleted: ['Kode sumber proyek', 'requirements.txt', 'Virtual environment', 'Paket yang sudah terinstall'],
  },
  {
    id: 'uv-cache',
    name: 'uv Cache',
    risk: 'safe-cache',
    description: 'Cache uv (manajer paket Python) di %LOCALAPPDATA%\\uv\\cache. Hanya folder cache terdeteksi; jangan hapus seluruh %LOCALAPPDATA%\\uv.',
    recommendedMethod: 'Verifikasi lokasi cache dengan uv cache dir terlebih dahulu, baru bersihkan.',
    cmdCommands: ['uv cache dir', 'uv cache clean'],
    psCommands: ['uv cache dir', 'uv cache clean'],
    warnings: ['Jangan hapus seluruh folder %LOCALAPPDATA%\\uv; hanya cache yang aman.', 'uv cache clean menghapus semua cache yang terdeteksi.'],
    whatWillHappen: ['Dependency perlu diunduh ulang saat project berikutnya dijalankan.'],
    whatWillNotBeDeleted: ['Kode sumber proyek', 'pyproject.toml', 'uv.lock', 'Paket yang sudah terinstall secara global'],
  },
  {
    id: 'windows-user-temp',
    name: 'Windows User Temp (%LOCALAPPDATA%\\Temp)',
    risk: 'safe-cache',
    description: 'File sementara aplikasi pengguna. File yang sedang digunakan akan ditolak oleh Windows (dilewati otomatis).',
    recommendedMethod: 'Tutup aplikasi, buka %TEMP% lewat File Explorer, hapus isi manual. Command agresif hanya untuk lanjutan.',
    cmdCommands: ['del /q /f /s "%TEMP%\\*" 2>nul', 'for /d %i in ("%TEMP%\\*") do rd /s /q "%i" 2>nul'],
    psCommands: ['Remove-Item -Path "$env:TEMP\\*" -Force -Recurse -ErrorAction SilentlyContinue'],
    warnings: ['Command agresif dapat mencoba menghapus file yang terkunci; file terkunci akan gagal dan dilewati.', 'Lebih aman: buka %TEMP% via Win+R, pilih isi, hapus manual, skip file terkunci.'],
    whatWillHappen: ['Aplikasi membuat file temp baru saat dibutuhkan.'],
    whatWillNotBeDeleted: ['File yang sedang digunakan aplikasi (akan error/terlewati)'],
  },
  {
    id: 'windows-temp',
    name: 'Windows System Temp (C:\\Windows\\Temp)',
    risk: 'safe-cache',
    description: 'File sementara tingkat sistem. Sebagian memerlukan Administrator untuk dihapus.',
    recommendedMethod: 'Jalankan Command Prompt sebagai Administrator, lalu bersihkan isi folder.',
    cmdCommands: ['del /f /q /s "C:\\Windows\\Temp\\*" 2>nul', 'for /d %i in ("C:\\Windows\\Temp\\*") do rd /s /q "%i" 2>nul'],
    psCommands: ['Remove-Item -Path "C:\\Windows\\Temp\\*" -Force -Recurse -ErrorAction SilentlyContinue'],
    warnings: ['Butuh hak Administrator.', 'File yang digunakan Windows akan ditolak (skip otomatis).', 'Jangan paksa hapus file sistem yang terkunci.'],
    whatWillHappen: ['Installer dan layanan Windows mengisi ulang folder ini.'],
    whatWillNotBeDeleted: ['File yang sedang digunakan Windows/layanan'],
  },
  {
    id: 'chrome-cache',
    name: 'Chrome Cache (Cache, Code Cache, GPUCache)',
    risk: 'safe-cache',
    description: 'Cache standar Chrome: Cache, Code Cache, GPUCache. Cookie, History, Password, Autofill TIDAK disentuh.',
    recommendedMethod: 'Cara paling aman: gunakan pengaturan bawaan Chrome untuk menghapus data browsing.',
    cmdCommands: [],
    psCommands: [],
    warnings: ['Hapus via chrome://settings/clearBrowserData → centang "Cached images and files" saja.', 'JANGAN hapus Cookie, Passwords, Autofill, History kecuali Anda memahami dampaknya.'],
    whatWillHappen: ['Situs dimuat sedikit lebih lambat saat pertama kali dikunjungi.', 'Cache dibangun ulang otomatis.'],
    whatWillNotBeDeleted: ['Cookies', 'Passwords', 'Autofill data', 'History', 'Bookmarks', 'Login Data', 'Preferences', 'Extension data'],
  },
  {
    id: 'chrome-service-worker',
    name: 'Chrome Service Worker CacheStorage',
    risk: 'review',
    description: 'CacheStorage digunakan website/PWA untuk offline storage dan resource caching. Bisa besar tapi berisi data offline aplikasi web.',
    recommendedMethod: 'Hapus data per website lewat pengaturan Chrome, bukan menghapus folder CacheStorage secara massal.',
    cmdCommands: [],
    psCommands: [],
    warnings: ['Menghapus seluruh CacheStorage dapat menghapus data offline website yang Anda gunakan (mis. Google Docs offline, PWA).', 'Gunakan chrome://settings/content/all → cari website → Remove site data.'],
    whatWillHappen: ['Website/PWA perlu mengunduh ulang resource offline saat dikunjungi lagi.'],
    whatWillNotBeDeleted: ['Cookie, Password, History, Bookmarks, Extension data, Profil Chrome'],
  },
  {
    id: 'gradle-cache',
    name: 'Gradle Cache (.gradle/caches)',
    risk: 'review',
    description: 'Cache dependency dan build Gradle. Menghapusnya memerlukan dependency diunduh ulang.',
    recommendedMethod: 'Hentikan daemon Gradle terlebih dahulu, lalu hapus isi folder caches secara manual.',
    cmdCommands: ['gradle --stop', 'rmdir /s /q "%USERPROFILE%\\.gradle\\caches"'],
    psCommands: ['gradle --stop', 'Remove-Item -Path "$env:USERPROFILE\\.gradle\\caches\\*" -Force -Recurse -ErrorAction SilentlyContinue'],
    warnings: ['JANGAN hapus gradle.properties, credentials, atau wrapper configuration di .gradle root.'],
    whatWillHappen: ['Dependency Gradle diunduh ulang saat build berikutnya.'],
    whatWillNotBeDeleted: ['gradle.properties', 'Gradle credentials', 'Wrapper configuration (gradle-wrapper.jar, gradle-wrapper.properties)'],
  },
  {
    id: 'docker-storage',
    name: 'Docker Storage',
    risk: 'review',
    description: 'Penyimpanan Docker (image, container, volume, build cache). Hanya informasi read-only; pembersihan butuh pertimbangan.',
    recommendedMethod: 'Gunakan docker system df untuk melihat penggunaan. Pembersihan via docker system prune -a HAPUS image/container/volume/cache yang tidak dipakai — pahami dampaknya.',
    cmdCommands: ['docker system df', 'docker system df -v'],
    psCommands: ['docker system df', 'docker system df -v'],
    warnings: ['docker system prune -a akan menghapus SEMUA image, container, network, build cache yang tidak digunakan.', 'docker volume prune dapat menghapus data persisten volume — JANGAN gunakan kecuali yakin.', 'Ini hanya informasi; aplikasi tidak mengeksekusi perintah Docker.'],
    whatWillHappen: ['Image/container/cache tidak terpakai dihapus; harus di-pull/build ulang.'],
    whatWillNotBeDeleted: ['Container yang berjalan', 'Image yang dipakai container aktif', 'Volume yang dipakai container aktif (kecuali volume prune)'],
  },
  {
    id: 'directx-cache',
    name: 'DirectX Shader Cache (D3DSCache, NVIDIA DXCache/GLCache)',
    risk: 'safe-cache',
    description: 'Cache shader DirectX/GPU. Aman dihapus; game/aplikasi membangun ulang saat dijalankan.',
    recommendedMethod: 'Hapus isi folder D3DSCache, NVIDIA DXCache, GLCache via File Explorer setelah tutup game.',
    cmdCommands: ['del /q /f /s "%LOCALAPPDATA%\\D3DSCache\\*" 2>nul', 'for /d %i in ("%LOCALAPPDATA%\\D3DSCache\\*") do rd /s /q "%i" 2>nul'],
    psCommands: ['Remove-Item -Path "$env:LOCALAPPDATA\\D3DSCache\\*" -Force -Recurse -ErrorAction SilentlyContinue'],
    warnings: ['Frame pertama game bisa tersendat sesaat saat shader dibangun ulang.'],
    whatWillHappen: ['Shader dibangun ulang otomatis saat game/aplikasi DirectX/OpenGL dijalankan.'],
    whatWillNotBeDeleted: ['Game saves', 'Config game', 'Driver GPU'],
  },
  {
    id: 'crash-dumps',
    name: 'Crash Dumps',
    risk: 'safe-cache',
    description: 'Dump aplikasi yang crash. Aman dihapus jika tidak sedang menganalisis masalah.',
    recommendedMethod: 'Hapus isi folder CrashDumps, Minidump, LiveKernelReports, WER ReportQueue/Archive via Disk Cleanup atau manual.',
    cmdCommands: [],
    psCommands: [],
    warnings: ['Jika sedang men-debug crash aplikasi, simpan dump terlebih dahulu.'],
    whatWillHappen: ['Riwayat crash dihapus; dump baru dibuat saat crash berikutnya.'],
    whatWillNotBeDeleted: ['Log sistem lain', 'Event logs'],
  },
];
function getGuide(id) { return GUIDES.find(g => g.id === id) || null; }
function getAllGuides() { return GUIDES.map(({ id, name, risk, description }) => ({ id, name, risk, description })); }
module.exports = { getGuide, getAllGuides, GUIDES };